### PR TITLE
Config option for furnace

### PR DESCRIPTION
**Pull request by Mr-Deej**
Prevents the usage of currencies within furnaces, as for the blast furnace check that cannot be done until the project starts building on spigot v1.14+.
This should partially close issue #125

### CODE REVIEW

**Review by dmccoystephenson — APPROVED** [review]

**Comment by dmccoystephenson** [comment]
I believe there's a method in the BlockChecker class in the Ponder library called "compatMaterial" that might come in handy here. It allows Medieval Factions to treat blast furnaces as furnaces even without utilizing later versions of Spigot.

**Comment by Mr-Deej** [comment]
i will check that out, ran into a bit of trouble with the real furnace as players are able to place into it but not take out. May need some help there but i believe the InventoryClickEvent is what needs to be used to complete issue #125

**Comment by Mr-Deej** [comment]
The two commits above this i moved to a different pull request as they do not fall in line with this one

**Comment by Mr-Deej** [comment]
This should work as expected

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me! Thank you for your contribution!

**Pull request merged**
